blog/accounts/urls.py
from django.conf.urls import url
from .views import *
from django.contrib import admin
from .forms import LoginForm

app_name = 'accounts'

admin.autodiscover()
urlpatterns = [

        url(r'^login/$', login_view, name='login'),

        url(r'^logout/$', logout_view, name='logout'),

        url(r'^register/$', register_view, name='register'),


]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404,handler500
from blog import views
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', home_view, name='home'),

    url(r'^post/', include('post.urls', namespace='post')),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url('^api/v1/', include('social_django.urls', namespace='social')),

    url(r'^users/', include('users.urls', namespace='users'))



]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = views.error404

blog/post/urls.py
from django.conf.urls import url
from .views import *

app_name = 'post'


urlpatterns = [

    url(r'^index/$', post_index, name='index'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/update', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete', post_delete, name='delete'),
    ]

blog/users/urls.py
from django.conf.urls import url
from .views import edit_profile, user_screen
from django.contrib import admin

app_name = 'users'
admin.autodiscover()
urlpatterns = [

        url(r'^(?P<username>.+)/screen_user/$', view=user_screen, name='user_screen'),
        url(r'^(?P<username>.+)/update/$',view=edit_profile , name='edit_profile')
]

blog/home/models.py
from django.db import models

# Create your models here.

blog/home/views.py
from django.shortcuts import render, reverse, HttpResponseRedirect
from post.models import Post
from django.contrib.auth.decorators import login_required
from social_django.models import AbstractUserSocialAuth
from social_django.models import UserSocialAuth
from accounts.models import UserProfile
import urllib.request, json



@login_required(login_url='/accounts/login/')
def home_view(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)
    social_auth=UserSocialAuth.objects.filter(user=request.user)
    if social_auth:
        usr = UserSocialAuth.objects.get(user=request.user)
        if usr.provider == 'facebook':
            import urllib.request, json

            with urllib.request.urlopen(
                                    "http://graph.facebook.com/v2.10/" + usr.uid + "/picture?redirect=false&fields=url") as url:
                data = json.loads(url.read().decode())
                print(data['data']['url'])
                print(usr.uid)

            user_profile.user_img_path = data['data']['url']
            user_profile.userImg = user_profile.user_img_path
            user_profile.control = True
            user_profile.save()
            print(request.user.profile.user_img_path)
    else:
        usr = None


    query = (request.GET.get('q', None))
    if query:
        url = reverse('post:index')
        url += '?q=' + query
        return HttpResponseRedirect(url)
    context = {'posts': Post.objects.all()}


    return render(request, 'home.html', context)

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, inital-scale=1">
    <title>{% block title %}Django Dersleri{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>



</head>
<body>



    {% include 'messages.html' %}
    {% include 'header.html' %}
    {% block body %}

    {% endblock %}



</body>
</html>

blog/templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-default navbar-fixed-top " role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">Django Dersleri</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="{% url 'post:index' %}">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{ request.GET.q }}"  >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara" >
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                 {% if request.user.is_superuser %}
                <li><a href="{% url 'post:create' %}">Yazı Ekle</a></li>
                 {% endif %}
                <li><a href="{% url 'home' %}">Anasayfa</a></li>
                <li><a href="{% url 'post:index' %}">Blog</a></li>
                <li><a href="#">Hakkımda</a></li>
                <li><a href="#">İletişim</a></li>

                    {% if not request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:register ' %}">Üye Ol</a></li>
                        <li><a href="{% url 'accounts:login' %}">Giriş Yap</a></li>
                    {% else %}


                         <li>

                        <ul class="nav navbar-right top-nav">

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="{% if request.user.profile.control == True %}{{request.user.profile.userImg }} {% endif %} {% if request.user.profile.control == False %}{{request.user.profile.userImg.url }}{% endif %}" class="img-circle"
                         style="width: 32px;height: 32px">
                   {% if request.user.profile.control != True %}  {{ request.user.username }} {% endif %} {% if request.user.profile.control == True %} {{ request.user.first_name}} {% endif %}<b
                        class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'users:user_screen' request.user.username %}"><i class="fa fa-fw fa-user"></i>
                            Profili Görüntüle</a>
                    </li>

                    <li>
                        <a href="{% url 'users:edit_profile' request.user.username %}"><i class="fa fa-fw fa-gear"></i> Ayarlar</a>
                    </li>

                    <li class="divider"></li>
                    <li>
                        <a href="{% url 'accounts:logout' %}"><i class="fa fa-fw fa-power-off"></i> Çıkış</a>
                    </li>
                </ul>
            </li>
        </ul>


                        </li>
                    {% endif %}
            </ul>

        </nav>

    </div>
</nav>

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

{% endblock %}

blog/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    {{ message }}
    {% endfor %}
       </div>
{% endif %}